# Generated by Django 6.1 on 2026-09-06 03:41

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_sellerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('scientific_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('category', models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('SUCCULENT', 'Succulent & Cactus'), ('FLOWERING', 'Flowering'), ('MEDICINAL', 'Medicinal & Herbs')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='accounts.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'price'], name='plants_plan_categor_b6b584_idx'), models.Index(fields=['is_available', 'stock_quantity'], name='plants_plan_is_avai_0bb45f_idx')],
            },
        ),
    ]
